namespace HR.CrossCutting.Enum;
public enum ObjectType
{
	Resource = 0,
	Project = 1,
	User = 2,
	Common = 3,
	Record = 4,
	Task = 5,
	Training = 6,
	CareerDevelopmentDay = 7,
	Achievement = 8,
	CareerDevelopmentDayLike = 9,
	CustomField = 10,
	Attendance = 11,
	CustomFieldReference = 12,
	CustomFieldValue = 13,
	Adaptation = 14,
	Permission = 15,
	Trainee = 16,
	Diary = 17,
	Mentor = 18,
	Mentee = 19,
	PersonnelReserve = 20,
	PositionResponse = 21,
	IndividualDevelopmentPlan = 22,
	IndividualDevelopmentPlanItem = 23,
	Dictionary = 24,
	DictionaryValue = 25,
	DismissalRequest = 26,
	KeyResource = 27,
	BypassSheet = 28,
	ShareResource = 29,
	ResourceOffer = 75,
	Candidate = 76,
	Gratitude = 77,
	BypassSheetRM = 101,
	BypassSheetOXO = 102,
	BypassSheetOSAiT = 103,
	BypassSheetHR = 104,

	Questionnaire = 30,
	QuestionnaireSe = 31,
	QuestionnaireQa = 32,
	QuestionnaireBa = 33,
	QuestionnairePm = 34,
	QuestionnaireAdaptation = 35,
	//Типы анкет по менторству
	QuestionnaireMentoringMentee = 36,
	QuestionnaireMentoringMentor = 37,
	QuestionnaireMentoringLead = 38,
	QuestionnaireMentoring = 39,
	QuestionnaireSupport = 40,
	//Типы анкет Lead
	QuestionnaireLeadSelf = 41,
	QuestionnaireLeadTeam = 42,
	QuestionnaireLeadBA = 43,
	QuestionnaireLeadResult = 44,
	QuestionnaireLeadSE = 45,
	QuestionnaireLead = 46,
	QuestionnaireRmTeam = 47,
	QuestionnaireRmCollegues = 48,
	QuestionnaireRmSelf = 49,
	QuestionnaireQaAutomation = 50,
	QuestionnaireAdaptationRM = 51,
	QuestionnaireSoft = 52,
	QuestionnaireSoftSelf = 53,
	Meeting = 60,
	MeetingOneToOne = 61,
	MeetingWithManager = 62,
	MeetingBeforeCdd = 63,
	MeetingOnWorkEfficiency = 64,
	MeetingOnCdd = 65,
	MeetingOnAdaptation = 66,
	MeetingOnMentoring = 67,
	MeetingOnTraining = 68,
	MeetingOnExitInterview = 69,
	QuestionnaireQaSelf = 145,
	QuestionaireQaTeam = 146,
	QuestionnaireBaSelf = 147,
	QuestionnaireBaTeam = 148,
	QuestionnaireCddFeedback = 149,
	QuestionnaireSESelf = 150,
	QuestionnaireSETeam = 151,
	QuestionnaireQaAutoSelf = 300,
	QuestionnaireQaAutoTeam = 301,
	QuestionnaireMentorship = 305,


	Mentoring = 70,
	MentoringRookie = 71, //Менторство новичка
	MentoringKnowledgeTransfer = 72, //Менторство по передаче знаний\опыта действующим сотрудникам
	MentoringOfManagment = 73, //Менторство управленческое
	QuestionnaireSeV2 = 74, 
	Mentorship = 217,

	WFAction = 90,
	None = 100,
	Direction = 200,
	Se = 202,
	Qa = 203,
	Ba = 204,
	Pm = 205,

	ExitInterview = 250,
	MeetingMentorship = 269,
	SecretSanta = 270,

	Booking = 500
}
